// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL095TPhr3otfT4arVw5HVOCZ8ySCiJis',
    appId: '1:175466914558:web:bb46a24659d869281c3baf',
    messagingSenderId: '175466914558',
    projectId: 'food-app-2e74a',
    authDomain: 'food-app-2e74a.firebaseapp.com',
    storageBucket: 'food-app-2e74a.firebasestorage.app',
    measurementId: 'G-Z2ESX80KX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX7BjML5PqTmmoex3K5p4ExzlZsRquMxs',
    appId: '1:175466914558:android:dd0c3e60f5195eb61c3baf',
    messagingSenderId: '175466914558',
    projectId: 'food-app-2e74a',
    storageBucket: 'food-app-2e74a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlnYiw5lknNnI-Wpe04E2Z93yHUG9OH_k',
    appId: '1:175466914558:ios:0ae36fb2884920d71c3baf',
    messagingSenderId: '175466914558',
    projectId: 'food-app-2e74a',
    storageBucket: 'food-app-2e74a.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlnYiw5lknNnI-Wpe04E2Z93yHUG9OH_k',
    appId: '1:175466914558:ios:0ae36fb2884920d71c3baf',
    messagingSenderId: '175466914558',
    projectId: 'food-app-2e74a',
    storageBucket: 'food-app-2e74a.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL095TPhr3otfT4arVw5HVOCZ8ySCiJis',
    appId: '1:175466914558:web:d1f616cc89919fc01c3baf',
    messagingSenderId: '175466914558',
    projectId: 'food-app-2e74a',
    authDomain: 'food-app-2e74a.firebaseapp.com',
    storageBucket: 'food-app-2e74a.firebasestorage.app',
    measurementId: 'G-V17SH5PE5E',
  );
}
